name: plantismash_tfbs_test
channels:
  - conda-forge
  - bioconda
dependencies:
  # Conda dependencies
  - python=3.8
  - glimmer
  - glimmerhmm
  - hmmer=3.3.2
  - bioconda/label/cf201901::hmmer2
  - fasttree=2.1.11       
  - diamond=2.0.15
  - muscle=3.8.31
  - prodigal
  - blast=2.12.0
  - cd-hit=4.8.1
  - libxml2=2.10.3
  - pplacer
  - ncbi-datasets-cli
  - unzip
  - biopython==1.76

 # Extras for TFBS and visualization
  - logomaker

  # Pip dependencies
  - pip
  - pip:
      - argparse
      - straight.plugin==1.4.0-post-1
      - cssselect
      - pyquery==1.2.9
      - numpy==1.24.4
      - helperlibs
      - svgwrite
      - openpyxl
      - networkx==3.1
      - python-louvain==0.16
      - bcbio-gff==0.6.7
      - ete3
      - ./graphlan
      # TFBS specific dependencies
      - MOODS-python

