SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;


CREATE SCHEMA antismashExtradata;


ALTER SCHEMA antismashExtradata OWNER TO biosql;


COMMENT ON SCHEMA antismashExtradata IS 'Storage of extra data generated by antiSMASH, eg. clusterblast, models';


